/*부진재고 대상 상품 수 및 그 리스트 內, 판매/재고처리/매가변경/점간이동 된 각각 상품 수*/				
WITH TEMP_TS_ST_SKU_PER_ACHIEVE AS				
(	SELECT A.ORIGIN_BIZPL_CD		
		 , A.GOODS_CD  		
		 , SUM(NVL(A.RTN_QTY * (-1), 0)) AS RTN_QTY		
		 , SUM(NVL(A.SALE_QTY, 0))  AS SALE_QTY		
		 , SUM(NVL(A.MV_STKOUT_QTY, 0) * (-1)) AS MV_STKOUT_QTY		
	FROM GSSCODS.TS_ST_SKU_PER_ACHIEVE A			
	WHERE 1 = 1			
	AND A.STK_EVAL_DT BETWEEN '20230901' AND '20230931'

	GROUP BY A.ORIGIN_BIZPL_CD, A.GOODS_CD
), 				
TEMP_TS_MS_PRC_CHG AS				
(		
SELECT B.ORIGIN_BIZPL_CD, A.GOODS_CD, COUNT(A.GOODS_CD) AS CHG_CNT		
  FROM LGMJVDP.TS_SL_PRC_CHG A
      ,LGMJVDP.TS_MS_BIZPL B
 WHERE 1 = 1
   AND A.BIZPL_CD = B.BIZPL_CD
   AND TO_CHAR(A.LAST_MODIFY_DTTM,'YYYYMM') = SUBSTRING('20230901',1,6)
GROUP BY B.ORIGIN_BIZPL_CD, A.GOODS_CD
) 	
   SELECT A.ORIGIN_BIZPL_CD  AS "최초점포코드"	   
         , D.BIZPL_NM  AS "점포명"
		 , COUNT(A.GOODS_CD) AS "부진재고 총 상품수"		
		 , SUM(CASE WHEN B.SALE_QTY > 0 THEN 1 ELSE 0 END) AS "판매 상품수"		
		 , SUM(CASE WHEN B.RTN_QTY > 0 THEN 1 ELSE 0 END) AS "재고처리 상품수"		
		 , SUM(CASE WHEN B.MV_STKOUT_QTY > 0 THEN 1 ELSE 0 END) AS "점간이동 상품수"		
		 , SUM(CASE WHEN C.CHG_CNT > 0 THEN 1 ELSE 0 END) AS "매가변경 상품수"		
	  FROM GSSCODS.TS_ST_MM_SLMP_STK A			
	  	 , TEMP_TS_ST_SKU_PER_ACHIEVE B		
	  	 , TEMP_TS_MS_PRC_CHG C
	  	 , GSSCODS.TS_MS_BIZPL D
	 WHERE 1 = 1
	   AND A.AGG_YYYYMM = SUBSTRING('202309',1,6)
	   AND A.ORIGIN_BIZPL_CD = B.ORIGIN_BIZPL_CD(+)		
	   AND A.GOODS_CD = B.GOODS_CD(+) 		
	   AND A.ORIGIN_BIZPL_CD = C.ORIGIN_BIZPL_CD(+)		
	   AND A.GOODS_CD = C.GOODS_CD(+) 		
	   AND A.ORIGIN_BIZPL_CD = D.ORIGIN_BIZPL_CD(+) 
       AND D.CLOSE_DT IS NULL
  GROUP BY A.ORIGIN_BIZPL_CD, D.BIZPL_NM
