WITH HEADER AS (
SELECT ORIGIN_BIZPL_CD
, OPER_DT
, POS_NO
, SALE_SEQ
FROM GSSCODS.TS_TR_HEADER
WHERE OPER_DT BETWEEN '20220301' AND '20220331'
AND DEAL_SP IN ('01','33','61') --정상판매 , 기프트콘 , 배달서비스
AND ORIGIN_BIZPL_CD = 'V9A21' --지에스타워점
)
,
ITEM AS (
SELECT ORIGIN_BIZPL_CD
, OPER_DT
, POS_NO
, SALE_SEQ
, GOODS_CD
, TO_CHAR(A.REGI_DTTM,'HH24') AS TIME_CD
, SUM(( A.DC_PRC * A.SALE_QTY ) - A.MBR_DC_AMT - A.PRMT_DC_AMT ) AS SALE_AMT
FROM GSSCODS.TS_TR_ITEM A
WHERE OPER_DT BETWEEN '20220301' AND '20220331'
AND ORIGIN_BIZPL_CD = 'V9A21' --지에스타워점
AND A.SKU_CANCEL_YN = 'N'
AND A.SALE_SP IN ('1','2','3') --정상판매 , 고객반품
GROUP BY ORIGIN_BIZPL_CD
, OPER_DT
, POS_NO
, SALE_SEQ
, GOODS_CD
, TO_CHAR(A.REGI_DTTM,'HH24')
)
SELECT SUBSTR(A.OPER_DT,1,6) AS 년월
, B.GOOD_CLS1CD AS 중분류코드
, B.GOOD_CLS1NM AS 중분류명
, SUM(CASE WHEN A.TIME_CD = '00' THEN A.SALE_AMT ELSE 0 END) AS 매출액_00
, SUM(CASE WHEN A.TIME_CD = '01' THEN A.SALE_AMT ELSE 0 END) AS 매출액_01
, SUM(CASE WHEN A.TIME_CD = '02' THEN A.SALE_AMT ELSE 0 END) AS 매출액_02
, SUM(CASE WHEN A.TIME_CD = '03' THEN A.SALE_AMT ELSE 0 END) AS 매출액_03
, SUM(CASE WHEN A.TIME_CD = '04' THEN A.SALE_AMT ELSE 0 END) AS 매출액_04
, SUM(CASE WHEN A.TIME_CD = '05' THEN A.SALE_AMT ELSE 0 END) AS 매출액_05
, SUM(CASE WHEN A.TIME_CD = '06' THEN A.SALE_AMT ELSE 0 END) AS 매출액_06
, SUM(CASE WHEN A.TIME_CD = '07' THEN A.SALE_AMT ELSE 0 END) AS 매출액_07
, SUM(CASE WHEN A.TIME_CD = '08' THEN A.SALE_AMT ELSE 0 END) AS 매출액_08
, SUM(CASE WHEN A.TIME_CD = '09' THEN A.SALE_AMT ELSE 0 END) AS 매출액_09
, SUM(CASE WHEN A.TIME_CD = '10' THEN A.SALE_AMT ELSE 0 END) AS 매출액_10
, SUM(CASE WHEN A.TIME_CD = '11' THEN A.SALE_AMT ELSE 0 END) AS 매출액_11
, SUM(CASE WHEN A.TIME_CD = '12' THEN A.SALE_AMT ELSE 0 END) AS 매출액_12
, SUM(CASE WHEN A.TIME_CD = '13' THEN A.SALE_AMT ELSE 0 END) AS 매출액_13
, SUM(CASE WHEN A.TIME_CD = '14' THEN A.SALE_AMT ELSE 0 END) AS 매출액_14
, SUM(CASE WHEN A.TIME_CD = '15' THEN A.SALE_AMT ELSE 0 END) AS 매출액_15
, SUM(CASE WHEN A.TIME_CD = '16' THEN A.SALE_AMT ELSE 0 END) AS 매출액_16
, SUM(CASE WHEN A.TIME_CD = '17' THEN A.SALE_AMT ELSE 0 END) AS 매출액_17
, SUM(CASE WHEN A.TIME_CD = '18' THEN A.SALE_AMT ELSE 0 END) AS 매출액_18
, SUM(CASE WHEN A.TIME_CD = '19' THEN A.SALE_AMT ELSE 0 END) AS 매출액_19
, SUM(CASE WHEN A.TIME_CD = '20' THEN A.SALE_AMT ELSE 0 END) AS 매출액_20
, SUM(CASE WHEN A.TIME_CD = '21' THEN A.SALE_AMT ELSE 0 END) AS 매출액_21
, SUM(CASE WHEN A.TIME_CD = '22' THEN A.SALE_AMT ELSE 0 END) AS 매출액_22
, SUM(CASE WHEN A.TIME_CD = '23' THEN A.SALE_AMT ELSE 0 END) AS 매출액_23
FROM ITEM A
JOIN LGMJVDP.TB_GOOD_DM B
ON A.GOODS_CD = B.GOODCD
JOIN HEADER C
ON A.ORIGIN_BIZPL_CD = C.ORIGIN_BIZPL_CD
AND A.OPER_DT = C.OPER_DT
AND A.POS_NO = C.POS_NO
AND A.SALE_SEQ = C.SALE_SEQ
GROUP BY SUBSTR(A.OPER_DT,1,6)
, B.GOOD_CLS1CD
, B.GOOD_CLS1NM
ORDER BY 1,2