select max(a13.RGNNM)  RGNNM,
max(a13.TEAM_LN)  TEAM_LN,
max(a13.PART_LN)  PART_LN,
max(a13.part_dist_seq)  part_dist_seq,
a11.STORECD  STORECD,
max(SUBSTR(a13.STORENM,1,INSTR(a13.STORENM,'(')-1 ))  STORENM,
max('V'||SUBSTR(a13.STORENM,INSTR(a13.STORENM,'(')+1, -( INSTR(a13.STORENM,'(') -INSTR(a13.STORENM,':'))-1))  CustCol_31,
a12.GOOD_CLS1CD  GOOD_CLS1CD,
max(a12.GOOD_CLS1NM)  GOOD_CLS1NM,
a11.GOODCD  GOODCD,
max(trim(trailing from a12.GOODNM))  GOODNM,
a11.RCT_IN_DATECD  최근입고일자,
sum(a11.CUR_STK_QTY)  현재재고,
a11.ORIGIN_VALID_DUR  유효기간,
a11.VALID_DUR  출고시유효기간
from LGMJVDP.TB_STORE_RCT_IN_AG a11
join LGMJVDP.TB_GOOD_DM a12
on  (a11.GOODCD = a12.GOODCD)
join LGMJVDP.TB_STORE_DM a13
on  (a11.STORECD = a13.STORECD)
where a12.GOOD_CLS1CD in ('58')
and a13.RGNCD in ('54')  
group by 
a11.STORECD,
a12.GOOD_CLS1CD,
a11.GOODCD,
a11.RCT_IN_DATECD,
a11.ORIGIN_VALID_DUR,
a11.VALID_DUR
having max(add_months(a11.RCT_IN_DATECD,SUBSTR(a11.ORIGIN_VALID_DUR,1,INSTR(a11.ORIGIN_VALID_DUR, '개월')-1))) < to_char(add_months(sysdate,1), 'YYYY-MM-DD')
